### ISSUE TITLE
JSON形式アップロード対応

### ISSUE THREAD

**Issue by watari3** [yukima77/covid-19-ishikawa-m5stack#10]
## 概要
JSON形式アップロード対応

## 詳細
PR #9 に記載されているようにmasterリポジトリに収集したデータをアップロードするコードを追加する

## 備考
octokitとアクセストークンで対応
アクセストークンについてはコミットしないファイルで対応
.gitignoreでコミット禁止としておくこと

**Comment by watari3** [comment]
@yukima77 
テストしたいのでdevelopブランチ作ってもらえますか

**Comment by yukima77** [comment]
@watari3 
テスト環境用にdevelopのブランチ作成しました。

**Comment by watari3** [comment]
コード書いていますがデータ管理用のブランチにコミットに変更したいです。

そのブランチに下記0バイトのファイルを作ってコミットしてもらえますか

- data/covid-19-fukui.json
- data/covid-19-ishikawa.json
- data/covid-19-toyama.json

**Comment by yukima77** [comment]
@watari3 
dataって名前でブランチを切って、上記のファイルを作っておきました。別ブランチの方が都合がよかったですか？

**Comment by watari3** [comment]
軽くしか見ていませんがこれでいけそうです。

続きの作業は会社から帰宅後行います。
以下本日の流れ(予定)

1. 石川版のJSON形式アップロード(セルフコミット)対応
[covid-19-ishikawa.json.txt](https://github.com/yukima77/covid-19-ishikawa-m5stack/files/4434578/covid-19-ishikawa.json.txt)

2. 1.の富山県版作成

3. 福井版作成

JSON形式のサンプル[ここ](https://github.com/yukima77/covid-19-ishikawa-m5stack/files/4434578/covid-19-ishikawa.json.txt)にありますので御覧ください。

**Comment by yukima77** [comment]
こちらは、JSONのサンプルあるので、これベースで処理できるようにM5Stack側の準備も進めます。
