### ISSUE TITLE
スクリプト実行環境対応

### ISSUE THREAD

**Issue by watari3** [yukima77/covid-19-ishikawa-m5stack#11]
## 概要
スクリプト実行環境の作成

## 詳細
とりあえずJenkinsかcronで実行できる環境を構築する。

## 備考
時間があればdockerでの対応を視野に入れる

**Comment by watari3** [comment]
シェルスクリプトに考慮漏れがあるので4/7中に修正する

**Comment by watari3** [comment]
.gitattributeの対応とshell script変更で対応する

PR #14 完了待ち

**Comment by yukima77** [comment]
@watari3 
マージしました。
