### ISSUE TITLE
JSON形式生成スクリプト

### ISSUE THREAD

**Issue by watari3** [yukima77/covid-19-ishikawa-m5stack#3]
## 概要
json形式ファイルを生成するスクリプト作成

## 詳細
とりあえず石川県の情報をjson形式化するruby スクリプトを作成する。
整理する情報は以下の通り

- 番号
- 性別
-  年齢
-  住所(市レベル)
-  管轄保健所
-  感染確定日
-  自覚開始日
-  ステータス

## 備考
追加情報あればコメント下さい
石川版出来上がれば、富山と福井のスクレイピングスクリプト作ります。

**Comment by yukima77** [comment]
これだけの情報があれば十分かと思います。いまの機能なら、とりあえず番号を拾ってくれば累計数が表示出来ます。

**Comment by watari3** [comment]
とりあえずこれだけのデータ取得するようにしました。

- 感染者番号
- 年代
- 性別
- 居住地
- 感染確定日

**Comment by watari3** [comment]
石川県版が完成したのでclose
